<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lsp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)^ [ \t]* \(
	  (?&lt;par&gt;
	    ( [^()\n]++ | \( \g&lt;par&gt; \)? )*+
	  )
	$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>newLISP</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;+ (mark|\!).*</string>
			<key>name</key>
			<string>comment.line.marker.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*TODO:.*</string>
			<key>name</key>
			<string>comment.line.todo.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^;; .*$\n?</string>
			<key>name</key>
			<string>comment.doc.lisp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;|#).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.lisp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.lisp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.paren.lisp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.functiondef.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(define|define\-\w*)\s+(\()\s*([\w/\-\+\!\?\.\*:&lt;&gt;=&amp;]+)</string>
			<key>name</key>
			<string>meta.function.lisp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lisp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lisp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lisp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.lisp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.lisp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.lisp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.quote.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;='\()([^\(\d"][\w/\-\!\?\.\+\*:&lt;&gt;=]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\()([^\(\)\d"\s][\w/\-\+\!\?\.\*:&lt;&gt;=&amp;]*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(</string>
			<key>name</key>
			<string>entity.paren.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\)</string>
			<key>name</key>
			<string>entity.paren.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:eq|neq|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:nil|true)\b</string>
			<key>name</key>
			<string>constant.language.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:cons|car|cdr|cond|lambda|format|setq|setf|quote|eval|append|list|load)\b</string>
			<key>name</key>
			<string>support.function.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-z_A-Z\*][\d\w\-\!\?\*:&lt;&gt;=]+</string>
			<key>name</key>
			<string>entity.symbol.lisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[+-]?\b(((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?)\b</string>
			<key>name</key>
			<string>constant.numeric.lisp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lisp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lisp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lisp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[text\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lisp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[\/text\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lisp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lisp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>entity.marker.lisp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.newlisp</string>
	<key>uuid</key>
	<string>2BA606BB-2AC3-4DCE-B7D2-6F9AF52C2751</string>
</dict>
</plist>
